export const STYLIST_SERVICE_LINK_MESSAGES = {
  SUCCESS: {
    CREATED: 'Legătura stilist-serviciu a fost creată cu succes.',
    DELETED: 'Legătura stilist-serviciu a fost ștearsă cu succes.',
    UPDATED: 'Legătura stilist-serviciu a fost actualizată cu succes.',
    REMOVED: 'Serviciul a fost eliminat cu succes.',
    ASSOCIATED: 'Serviciu asociat cu succes!',
  },
  ERROR: {
    ALREADY_EXISTS: 'Această legătură există deja.',
    NOT_FOUND: 'Legătura stilist-serviciu nu a fost găsită.',
    CREATE_FAILED: 'Nu s-a putut crea legătura stilist-serviciu.',
    DELETE_FAILED: 'Nu s-a putut șterge legătura stilist-serviciu.',
    UPDATE_FAILED: 'Nu s-a putut actualiza legătura stilist-serviciu.',
    VALIDATION: 'Eroare de validare la ștergere.',
    GENERIC: 'A apărut o eroare la ștergere.',
  },
  UI: {
    ADD_BUTTON: 'Adaugă Serviciu',
    ADD_TITLE: 'Adaugă un Serviciu pentru Stilist',
    EDIT_TITLE: 'Editează serviciul asociat',
    EDIT_BUTTON: 'Salvează Modificările',
    DELETE_CONFIRM_TITLE: 'Ești sigur că vrei să elimini serviciul?',
    DELETE_CONFIRM_DESC: (serviceName: string) =>
      `Această acțiune nu poate fi anulată. Serviciul ${serviceName} va fi eliminat din lista stilistului.`,
    TABLE_EMPTY_TITLE: 'Niciun serviciu asociat',
    TABLE_EMPTY_DESC: 'Adaugă un serviciu pentru acest stilist.',
    FORM_SERVICE_LABEL: 'Serviciu',
    FORM_PRICE_LABEL: 'Preț personalizat',
    FORM_DURATION_LABEL: 'Durată personalizată (minute)',
    FORM_PLACEHOLDER_PRICE: 'Lasă necompletat pentru preț standard',
    FORM_PLACEHOLDER_DURATION: 'Lasă necompletat pentru durata standard',
    TABLE_HEADER_NAME: 'Nume',
    TABLE_HEADER_CATEGORY: 'Categorie',
    TABLE_HEADER_PRICE: 'Preț standard',
    TABLE_HEADER_DURATION: 'Durată standard',
    TABLE_HEADER_CUSTOM_PRICE: 'Preț personalizat',
    TABLE_HEADER_CUSTOM_DURATION: 'Durată personalizată',
    TABLE_HEADER_ACTIONS: 'Acțiuni',
  },
}
